from enum import Enum
class Specialty(Enum):
  IMMUNOLOGY = 1
  DERMATOLOGY = 2
  CARDIOLOGY = 3
  ENDOCRINOLOGY = 4
  GASTROENTEROLOGY = 5
  HEMATOLOGY = 6
  NEUROLOGY = 7
  ONCOLOGY = 9
  OTALARYNGOLOGY = 10
  PODIASTRIST = 11
  UROLOGY = 12
  GENERAL = 13
